# Generated by Django 4.2.7 on 2026-01-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="rank",
            field=models.CharField(default="Bronze", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_submissions_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="accepted_submissions_count",
            field=models.IntegerField(default=0),
        ),
    ]
