# Generated by Django 4.2.7 on 2025-12-31 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text="User's submitted code")),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('csharp', 'C#'), ('cpp', 'C++')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error'), ('internal_error', 'Internal Error')], default='pending', max_length=30)),
                ('test_results', models.JSONField(blank=True, help_text='Detailed test case results', null=True)),
                ('execution_time', models.IntegerField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('memory_used', models.IntegerField(blank=True, help_text='Memory used in MB', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if submission failed', null=True)),
                ('points_awarded', models.IntegerField(default=0, help_text='Points awarded for this submission')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'problem'], name='submissions_user_id_1304bb_idx'), models.Index(fields=['status'], name='submissions_status_c2b4f2_idx'), models.Index(fields=['submitted_at'], name='submissions_submitt_f62c88_idx')],
            },
        ),
    ]
