# Generated by Django 4.2.7 on 2026-01-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this solution is publicly shared'),
        ),
        migrations.AddField(
            model_name='submission',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When the solution was made public', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='solution_description',
            field=models.TextField(blank=True, help_text='Optional description/comment about the solution approach', null=True),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'is_public', 'execution_time'], name='submissions_problem_07eeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['is_public', '-published_at'], name='submissions_is_publ_7c22e3_idx'),
        ),
    ]
