# Generated by Django 4.2.7 on 2025-12-31 19:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Problem description with examples and constraints"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Łatwe"),
                            ("medium", "Średnie"),
                            ("hard", "Trudne"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Experience points awarded for solving",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "languages",
                    models.CharField(
                        default="python,javascript,csharp,cpp",
                        help_text="Comma-separated list of supported languages",
                        max_length=100,
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=2000, help_text="Time limit in milliseconds"
                    ),
                ),
                (
                    "memory_limit",
                    models.IntegerField(default=128, help_text="Memory limit in MB"),
                ),
                (
                    "function_signature_python",
                    models.TextField(
                        blank=True,
                        help_text="Python function signature/template",
                        null=True,
                    ),
                ),
                (
                    "function_signature_javascript",
                    models.TextField(
                        blank=True,
                        help_text="JavaScript function signature/template",
                        null=True,
                    ),
                ),
                (
                    "function_signature_csharp",
                    models.TextField(
                        blank=True,
                        help_text="C# function signature/template",
                        null=True,
                    ),
                ),
                (
                    "function_signature_cpp",
                    models.TextField(
                        blank=True,
                        help_text="C++ function signature/template",
                        null=True,
                    ),
                ),
                ("total_submissions", models.IntegerField(default=0)),
                ("accepted_submissions", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem",
                "verbose_name_plural": "Problems",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.TextField(
                        help_text="Input data for the test case (can be JSON)"
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(help_text="Expected output for the test case"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden test cases are not shown to users",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of test case execution"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Case",
                "verbose_name_plural": "Test Cases",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProblemTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "problems",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="problems.problem"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProblemHint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hints",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hint",
                "verbose_name_plural": "Hints",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["difficulty"], name="problems_pr_difficu_d3b056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["created_at"], name="problems_pr_created_b0f0ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(fields=["slug"], name="problems_pr_slug_19f4ac_idx"),
        ),
    ]
